name: generate animation

on:
  # Chạy tự động mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *" 
  
  # Cho phép chạy thủ công bất cứ lúc nào
  workflow_dispatch:
  
  # Chạy mỗi khi bạn push code vào nhánh main
  push:
    branches:
    - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Tạo ra con rắn từ biểu đồ đóng góp của TanVi3001
      - name: generate github-contribution-grid-snake.svg
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: TanVi3001
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Đẩy file ảnh con rắn lên nhánh 'output' để hiển thị
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
